### PR TITLE
change useUpdate hook to use `reducer` instead of `state + callback`

### PR DESCRIPTION
**Pull request by MHA15**
if we using reducer instead of useState then we don't need a useCallback and it's performance will increase

### CODE REVIEW

**Comment by streamich** [comment]
> ... and it's performance will increase

Why do you think performance will increase?

**Comment by MHA15** [comment]
> > ... and it's performance will increase
> 
> Why do you think performance will increase?

no need to use `useCallback` and have no inline function

**Comment by MHA15** [comment]
@streamich 
Don't you agree that this implementation is better than old one (epsilon better) ?

**Pull request merged**
