### PR TITLE
feat: add useStateList

### PR DESCRIPTION
**Pull request by d-asensio**

### CODE REVIEW

**Comment by xobotyi** [comment]
Hook name is extremely unintuitive😵

**Comment by d-asensio** [comment]
@xobotyi I agree 👍 any proposal?

`useStateRotate`
`useListRotate`

😅

**Comment by xobotyi** [comment]
`useArrayIterate`
`useListIterate`

**Comment by d-asensio** [comment]
mmm... But the term 'iterate' is missing the important part of this hook... it returns to the first element when reaches the last element of the array. So it is a [circular shift](https://en.wikipedia.org/wiki/Circular_shift).

`useCircularShift`??

**Comment by d-asensio** [comment]
Maybe `useCircularIterate` is more appropriate since we are not shifting (that implies modification) the array. Just iterating it in a circular way.

**Comment by xobotyi** [comment]
@d-asensio this one looks good.

**Comment by d-asensio** [comment]
@xobotyi done!

**Comment by streamich** [comment]
This is basically a *finite state machine* with *state transitions* being adjacent list elements. Maybe we can call it something like `useStateList`? And change interface to:

```js
const { state, next, prev } = useStateList({ list, circular: true });
```

**Comment by d-asensio** [comment]
@streamich Yes! That's the idea! I use it as a _finite state machine_, specifically to control the animation phases of a [`<Collapsible />` component](https://codesandbox.io/s/collapsiblecomponent-w8xjn).

So I agree with the proposed interface!

I'll submit a PR with the corresponding changes during tomorrow ;)

**Comment by d-asensio** [comment]
@streamich @xobotyi done!

**Pull request merged**
