### PR TITLE
Add react use downloader

### PR DESCRIPTION
**Pull request by olavoparno**
# Description

This hook is inteded to help on download links in react providing info such as progress, time elapsed and cancel ability.

## Type of change

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] **Breaking change** _(fix or feature that would cause existing functionality to not work as before)_

# Checklist
- [X] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [X] Perform a code self-review
- [X] Comment the code, particularly in hard-to-understand areas
- [X] Add documentation
- [X] Add hook's story at Storybook
- [X] Cover changes with tests
- [X] Ensure the test suite passes (`yarn test`)
- [ ] Provide 100% tests coverage
- [X] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [X] Make sure types are fine (`yarn lint:types`).

### CODE REVIEW

**Comment by xobotyi** [comment]
@streamich wdyt?

**Comment by olavoparno** [comment]
> @streamich wdyt?
> Looks okay but im not sure that it should be a part of react-use. Too complex and have too few usecases IMO.
> Good one to be a separate hook though.

Thank you for the feeback, @xobotyi :) Regarding its complexity, do you refer to its usability or the very code implementation? Is there anything I could do to improve it?

**Comment by xobotyi** [comment]
@olavoparno its about overall complexity both code and things it tries to achieve.
As i see it, `react-use` should be the toolbox with maximally simple hooks to help developers to make their apps and also hooks. But this hook will be used by, well, it would be good if 1 percent of our users, other 99% will have to download useless for them codebase (and in case of poor packaging configuration it will also affect their bundle size).
But its my opinion, @streamich is the owner and its all up to him.

**Comment by xobotyi** [comment]
@olavoparno about the code - it is pretty much fine, except some non-critical moments, that are more about my code-style (гnfortunately dont have much time now to deep dive and show how wold i do them "my way")

**Comment by olavoparno** [comment]
> @olavoparno about the code - it is pretty much fine, except some non-critical moments, that are more about my code-style (гnfortunately dont have much time now to deep dive and show how wold i do them "my way")

you're definitely right, man. Thanks for the feedback, I really appreciate it.

**Pull request closed without merging**
