### PR TITLE
useMouse whenHovered option

### PR DESCRIPTION
**Pull request by wardoost**
Added `whenHovered` option as the second parameter similar to [`MouseSensor`](https://github.com/streamich/libreact/blob/master/docs/en/MouseSensor.md) from libreact. I also made the demo cute.

### CODE REVIEW

**Comment by wardoost** [comment]
I added an `enabled` argument to `useHoverDirty` to make it controllable. This means it can be reused for this `whenHovered`. It's the same pattern as the `enabled` option in `useLockBodyScroll`, not sure if it's a good pattern 😬

**Comment by wardoost** [comment]
Maybe a `disable` argument is better than `enabled`?

**Comment by streamich** [comment]
+1 for the emoji demo :)

**Pull request merged**
