### PR TITLE
fix(#785): update useStorage to use createGlobalState

### LINKED ISSUE #785: useLocalStorage not updating if many components watch the same key
Note: I'm already working on a PR for this.

**What is the current behavior?**
Multiple calls to `useLocalStorage('myKey')` from different components are not staying in sync as the value changes.

**Steps to reproduce it and if possible a minimal demo of the problem.**

Seems that all the Sandboxes are failing to install `react-use` right now but slap this somewhere and the problem will become apparent:

```js
import useLocalStorage from 'react-use/lib/useLocalStorage';

const Increment = () => {
  const [count, setCount] = useLocalStorage('count', 0);
  return (<h1 onClick={() => setCount(count+1)}>Increment</h1>);
}

const Decrement = () => {
  const [count, setCount] = useLocalStorage('count', 0);
  return (<h1 onClick={() => setCount(count-1)}>Decrement</h1>);
}

const App = () => (
  <>
    <Increment />
    <Decrement />
  </>
)
```

Basically it's _initializing_ from localStorage into individual instances of `useState` and then never reading from localStorage again, so if it's changed out from under you... (1) you never see the update and (2) if _you_ update it you clobber whatever was there before.

**What is the expected behavior?**

If my localStorage value changes, all my components watching that value pick up the change.

### PR DESCRIPTION
**Pull request by nspaeth**
# Description

Fixes #785 - useLocalStorage not updating if many components watch the same key

Previously pr #786 addressed this issue by ensuring that other components
watching the key would see new updates, however, those updates would not be
rendered until something else triggered a re-render. This pr resolves that issue.

This pull request depends on pull requests #1021 #979

## Type of change

- [x] Bug fix _(non-breaking change which fixes an issue)_
- [x] New feature _(non-breaking change which adds functionality)_
- ~~**Breaking change** _(fix or feature that would cause existing functionality to not work as before)_~~

# Checklist
- [x] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [x] Perform a code self-review
- [x] Comment the code, particularly in hard-to-understand areas
- [x] Add documentation
- [x] Add hook's story at Storybook
- [x] Cover changes with tests
- [x] Ensure the test suite passes (`yarn test`)
- [x] Provide 100% tests coverage
- [x] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [x] Make sure types are fine (`yarn lint:types`).

### CODE REVIEW

**Comment by zicodeng** [comment]
Wonder when this PR will get merged 🤔

**Comment by nspaeth** [comment]
:shrug: Maybe thumbs up the relevant issues and PRs to get it more attention?

**Comment by manishsundriyal** [comment]
Not sure, if someone is reviewing the recent issues or PRs.

**Comment by zicodeng** [comment]
@streamich Hi, thanks for creating this library. I understand you are a busy man. Can you take a look at this PR and merge it. This is a very important fix. Thank you

**Comment by zicodeng** [comment]
Does anyone know a good alternative library to this feature

**Pull request closed without merging**
