### PR TITLE
Update useAsync.ts

### PR DESCRIPTION
**Pull request by sunxing102005**
add arguments to async function

### CODE REVIEW

**Comment by wardoost** [comment]
@sunxing102005 Could you give an example where this would be necessary?

**Comment by sunxing102005** [comment]
if the async function has parameters ,the old useAsync can not add them.
```
const fn = (param)=>{
//it is an async function to fetch data
 return axios(param);
}
//we use the old useAsync like this
const state = useAsync(fn);
// but no way to set fn its params

//after my edit,we can use it like this
const state = useAsync(fn,[],param);

```

**Comment by wardoost** [comment]
Wouldn't you write that like this?
```js
const state = useAsync(() => {
  return axios(param);
}, [param]);
```
This is more in line with the API design of React's standard hooks. Besides that the `param` variable is probably coming from the props or state of the component it is used in. So if these parameters change your async function needs to be triggered again so you want to add `param` to the hook's dependencies.

**Comment by sunxing102005** [comment]
yes you are right, that 's a better solution, and  thank you for the interpretation！

**Comment by wardoost** [comment]
Np 👌

**Pull request closed without merging**
