### PR TITLE
Pr/eslint fix

### PR DESCRIPTION
**Pull request by ayush987goyal**
# Description

First step for #947 and #371 

1. Add eslint config
2. Add `eslint-disable` to affected files. 

## Type of change

- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] **Breaking change** _(fix or feature that would cause existing functionality to not work as before)_

# Checklist
- [x] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [x] Perform a code self-review
- [x] Comment the code, particularly in hard-to-understand areas
- [x] Add documentation
- [x] Add hook's story at Storybook
- [x] Cover changes with tests
- [x] Ensure the test suite passes (`yarn test`)
- [x] Provide 100% tests coverage
- [x] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [x] Make sure types are fine (`yarn lint:types`).

### CODE REVIEW

**Comment by xobotyi** [comment]
1) Why flowtype plugin is there?
2) What the sence to add esling and disable it for most part of the project? >_>

**Comment by ayush987goyal** [comment]
@xobotyi 
1. It is a dependency of `eslint-plugin-react-app`
2. Please refer #371 and #947

**Comment by wardoost** [comment]
Does this need a major version bump as mentioned in https://github.com/streamich/react-use/pull/371#issuecomment-575873311?

**Comment by streamich** [comment]
@wardoost does not seem to have any breaking changes to me. @ayush987goyal are there any breaking changes here? If yes, we can merge this into `v14.0` branch.

**Comment by ayush987goyal** [comment]
@streamich This PR does not have any breaking changes though the next PRs for individual hooks might have some.

**Pull request merged**
