### PR TITLE
chore(deps): update peerDependencies for react 18

### PR DESCRIPTION
**Pull request by skratchdot**
# Description

When installing `react-use` in a project with react 18 you might see the errors:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: myproject@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   dev react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0  || ^17.0.0" from react-use@17.3.2
npm ERR! node_modules/react-use
npm ERR!   dev react-use@"^17.3.2" from the root project
```

Workaround is using `npm install --force`

## Type of change

- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] **Breaking change** _(fix or feature that would cause existing functionality to not work as before)_

# Checklist
- [x] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [x] Perform a code self-review
- [x] Comment the code, particularly in hard-to-understand areas
- [x] Add documentation
- [x] Add hook's story at Storybook
- [x] Cover changes with tests
- [x] Ensure the test suite passes (`yarn test`)
- [x] Provide 100% tests coverage
- [x] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [x] Make sure types are fine (`yarn lint:types`).

### CODE REVIEW

**Comment by nikeee** [comment]
Fixes #2311

**Comment by suprMax** [comment]
Really looking forward to see this published guys, last dependency not supporting react@18 in my project

**Review by streamich — APPROVED** [review]
Thank you!

**Pull request merged**
