### PR TITLE
feat(useWait): remove useWait hook

### PR DESCRIPTION
**Pull request by xobotyi**
As an implementation of #708

### CODE REVIEW

**Comment by streamich** [comment]
Shall we make it a breaking change? I.e. delay merging until we release next major.

**Comment by xobotyi** [comment]
@streamich i'm pretty sure that all react-wait users are using directly react-wait's hook.
I think we can make a **patch** version with a deprecation message and **minor** version with deleted hook, IMO no sense to wait untill the major (actually i want to do some library sources sanitization before v13 release).

**Comment by xobotyi** [comment]
Also `react-wait` is abandoned already for a year and it's types defenition beaks most of current react version upgrades. #622 #577 #686 and soo on strictly related to react and typescript

**Pull request merged**
