### PR TITLE
feat: improve implementation of useFirstMountState() hook

### PR DESCRIPTION
**Pull request by LeoooY**
# Description

Improve implementation of useFirstMountState() hook.
I think use `useEffect` can be more efficient when frequently re-rendering 

## Type of change

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] **Breaking change** _(fix or feature that would cause existing functionality to not work as before)_

# Checklist
- [ ] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [x] Perform a code self-review
- [ ] Comment the code, particularly in hard-to-understand areas
- [ ] Add documentation
- [ ] Add hook's story at Storybook
- [ ] Cover changes with tests
- [ ] Ensure the test suite passes (`yarn test`)
- [ ] Provide 100% tests coverage
- [ ] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [ ] Make sure types are fine (`yarn lint:types`).

### CODE REVIEW

**Comment by xobotyi** [comment]
It won't be effective because instead of regular comparison on each render your impelemtation will create new function and call `useEffect` hook.

**Comment by LeoooY** [comment]
Since the deps of `useEffect` is `[]`, the effect will only run once when the component mounts and never run again. The old way will assign to `isFirst.current` on every render, I think it`s unnecessary.

**Comment by xobotyi** [comment]
`[]` deps only means that provided function will be called once on first mount, but provided function itself will be dynamically created on each render.

**Comment by xobotyi** [comment]
So if we will list the step-by-step execution log:

originally:
- get ref with default to `true`
- check `isFirst.current` is truthy
  - if truthy - assign `false`
  - return `true`
- return `isFirst.current` if falsy (actually it could be simplifier to `return false;`)

this PR:
- get ref with default to `true`
- create anonimous function
- create empty array
- pass them to `useEffect`
  - *inside `useEffect`*
    - check if dependencies contents changed
      - if changed - call provided function
- return `isFirst.current`

**Comment by LeoooY** [comment]
Thanks for your patient explanation, I think I get the point.

**Pull request closed without merging**
