### PR TITLE
feat: add useHash hook

### PR DESCRIPTION
**Pull request by whinc**
# Description

`const [hash, setHash] = useHash()`

get/set url hash value.

- `hash: string`: get current url hash. listen to `hashchange` event.
- `setHash: (newHash: string) => void`: change url hash. Invoke this method will trigger `hashchange` event similar to assign value to `window.location.hash`.

```jsx
import {useHash} from 'react-use';

const Demo = () => {
  const [hash, setHash] = useHash();

  useMount(() => {
    setHash('#/path/to/page?userId=123');
  });

  return (
    <div>
      <div>window.location.href:</div>
      <div>
        <pre>{window.location.href}</pre>
      </div>
      <div>Edit hash: </div>
      <div>
        <input style={{ width: '100%' }} value={hash} onChange={e => setHash(e.target.value)} />
      </div>
    </div>
  );
};
```

## Type of change

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [x] New feature _(non-breaking change which adds functionality)_
- [ ] **Breaking change** _(fix or feature that would cause existing functionality to not work as before)_

# Checklist
- [x] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [x] Perform a code self-review
- [ ] Comment the code, particularly in hard-to-understand areas
- [x] Add documentation
- [x] Add hook's story at Storybook
- [x] Cover changes with tests
- [x] Ensure the test suite passes (`yarn test`)
- [x] Provide 100% tests coverage
- [x] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [x] Make sure types are fine (`yarn lint:types`).

### CODE REVIEW

**Comment by xobotyi** [comment]
LGTM

**Comment by ranisalt** [comment]
I'm curious about the use case. Something similar but much more powerful can be achieved with `react-router`'s `HashRouter` and `useLocation`.

**Comment by whinc** [comment]
> I'm curious about the use case. Something similar but much more powerful can be achieved with `react-router`'s `HashRouter` and `useLocation`.

I think providing simple and usable hooks for a certain scenario will make it easier to get started and less prone to errors.

`useHash` is focused on reading and writing hash. Its interface is very simple. As a low-level function, we can derive more Hash-based hooks on this basis, such as` useHashSearchParams`(I will create another PR for this after this PR is merged).

```javascript
// 示例：http://a/b/c#/a/b/c?id=1&name=jim
const [id, setId] = useHashSearchParams('id')  // id: "1"
const [params, setParams] = useHashSearchParams()  // params: {id: "1", name: "jim"}

<button onClick={() => setId("2")}>Goto id 2</button>
```

**Comment by ranisalt** [comment]
That's sweet. I even think that for static SPAs relying on hash routes it can drop entirely the dependency on react-router, as you can use a JS `switch` instead :+1:

**Comment by whinc** [comment]
Is this PR actived?

**Comment by whinc** [comment]
👏

**Pull request merged**
