### PR TITLE
chore: Fix linting in CI

### PR DESCRIPTION
**Pull request by kachkaev**
# Description

## Type of change

- [ ] ~~Bug fix _(non-breaking change which fixes an issue)_~~
- [ ] ~~New feature _(non-breaking change which adds functionality)_~~
- [ ] ~~**Breaking change** _(fix or feature that would cause existing functionality to not work as before)_~~
- [x] Chore

# Checklist
- [x] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [x] Perform a code self-review
- [x] Comment the code, particularly in hard-to-understand areas
- [ ] ~~Add documentation~~
- [ ] ~~Add hook's story at Storybook~~
- [ ] ~~Cover changes with tests~~
- [ ] ~~Ensure the test suite passes (`yarn test`)~~
- [ ] ~~Provide 100% tests coverage~~
- [x] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [ ] ~~Make sure types are fine (`yarn lint:types`).~~

### CODE REVIEW

**Comment by streamich** [comment]
Can you please add `yarn lint` to `.github/workflows/pull_request_ci.yml`?

**Review by streamich — COMMENTED** [review]
Can you please `add yarn` lint to `.github/workflows/pull_request_ci.yml`?

**Comment by kachkaev** [comment]
Yep, sure

**Comment by kachkaev** [comment]
If you want, we can separate builds and linting into separate jobs – this will improve the quality of CI feedback. Example setup: https://github.com/gicentre/prettier-plugin-elm/blob/main/.github/workflows/check-codebase.yml

[Output](https://github.com/gicentre/prettier-plugin-elm/actions):

Screenshot 2021-08-31 at 23 10 20

Happy to do that in a separate PR if you want 🙂

**Review by streamich — APPROVED** [review]
Thank you!

> If you want, we can separate builds and linting into separate jobs – this will improve the quality of CI feedback.

That would be great.

**Pull request merged**
