### PR TITLE
Add useMeasureDirty to index

### PR DESCRIPTION
**Pull request by Goldskin**
# Description

We can't access useMeasureDirty!

## Type of change

- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] **Breaking change** _(fix or feature that would cause existing functionality to not work as before)_

# Checklist
- [x] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [x] Perform a code self-review
- [ ] Comment the code, particularly in hard-to-understand areas
- [ ] Add documentation
- [ ] Add hook's story at Storybook
- [ ] Cover changes with tests
- [x] Ensure the test suite passes (`yarn test`)
- [x] Provide 100% tests coverage
- [x] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [x] Make sure types are fine (`yarn lint:types`).

### CODE REVIEW

**Comment by jakemhiller** [comment]
@streamich any reason this couldn't be merged?

**Comment by andidev** [comment]
@streamich bump, this really is just an export

**Comment by kamilmielnik** [comment]
Bump :pray:

**Comment by glompix** [comment]
bump!

**Comment by as-zlynn-philipps** [comment]
@streamich bump

**Comment by Zertz** [comment]
As described in [this comment](https://github.com/streamich/react-use/pull/999#issuecomment-608648700), it is possible to import the hook directly.

**Comment by dzcpy** [comment]
Any updates? @streamich

**Pull request closed without merging**
