### PR TITLE
fix: allow only for client

### LINKED ISSUE #1195: useHash is not SSR compatible
**What is the current behavior?**

Error `window is undefined` is thrown`

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

Just use `useHash()` on SSR project.

**What is the expected behavior?**

If there isn't `window` object use some default values.

### PR DESCRIPTION
**Pull request by sungwoo91**
Fix #1195
 
# Description

Add line to check if it is a client.

## Type of change

- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] **Breaking change** _(fix or feature that would cause existing functionality to not work as before)_

# Checklist
- [x] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [x] Perform a code self-review
- [ ] Comment the code, particularly in hard-to-understand areas
- [ ] Add documentation
- [ ] Add hook's story at Storybook
- [x] Cover changes with tests
- [x] Ensure the test suite passes (`yarn test`)
- [x] Provide 100% tests coverage
- [x] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [x] Make sure types are fine (`yarn lint:types`).

### CODE REVIEW

**Comment by whinc** [comment]
I agree @streamich  . I think we should keep the client side and  server  side logic individual for better maintainability.

**Comment by sungwoo91** [comment]
@streamich @whinc 
Thanks for your help! I'll fix it soon.

**Comment by sungwoo91** [comment]
@streamich 
I changed the code with your advice. sorry for late!

**Comment by kachkaev** [comment]
This solution may lead to issues with DOM rehydration. For example, a Next.js app expects the Client DOM after the first render to match the DOM that SSR phase produced. So in order to make things fully SSR compatible, we'll need to start ignore `window.location.hash` on the client during the first render and then sync up in `useEffect.` This is will solve SSR rehydration but will probably received not so well by the client-only apps. So how about introducing a new hook instead of 'fixing' an existing one?

**Comment by mmahalwy** [comment]
any update to this? :)

**Pull request closed without merging**
