### PR TITLE
Flag to track if useMouseHovered is dirty

### PR DESCRIPTION
**Pull request by blnk-space**
A solution to #478 

We could use NaN/null/undefined etc. for the variable values (i.e. docX, docY, elX and elY) but that would translate to poor DX overall. Moreover, it would break backward compatibility.

It would be much easier for those who are concerned with making updates after the mouse has moved once, to be able to wrap all their logic in a block that checks if the mouse has moved once, whilst the original values still stay 0 and not null or something.

I have given the name "dirty" to this flag.

Let me know what you think!

### CODE REVIEW

**Comment by blnk-space** [comment]
@thevtm does this solve your use case as well?

@xobotyi what do you think?

**Comment by thevtm** [comment]
It's a nice solution.

I would change the name of the flag to something like "touched".

**Comment by streamich** [comment]
Can we check `elW`, `elH` for "dirtiness"?

```ts
const {docX, docY, posX, posY, elX, elY, elW, elH, dirty} = useMouse(ref);
const isDirty = !elW;
```

Also, `docX` and `docY` could probably be set from the very beginning. Other values could possibly be set faster if we used `useLayoutEffect` hook instead of `useEffect`.

**Comment by blnk-space** [comment]
@streamich yes that does make sense and works without changing the API.

**Pull request closed without merging**
