### PR TITLE
Enable declaration map

### PR DESCRIPTION
**Pull request by septs**
# Description

Enable `declarationMap` to directly from `declaration` and locate the typescript source code

see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---declarationmap

## Type of change

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [x] New feature _(non-breaking change which adds functionality)_
- [ ] **Breaking change** _(fix or feature that would cause existing functionality to not work as before)_

# Checklist
- [x] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [x] Perform a code self-review
- [x] Comment the code, particularly in hard-to-understand areas
- [x] Add documentation
- [x] Add hook's story at Storybook
- [x] Cover changes with tests
- [x] Ensure the test suite passes (`yarn test`)
- [x] Provide 100% tests coverage
- [x] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [x] Make sure types are fine (`yarn lint:types`).

### CODE REVIEW

**Comment by septs** [comment]
see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---declarationmap

**Comment by septs** [comment]
@streamich

**Comment by septs** [comment]
@xobotyi

**Comment by xobotyi** [comment]
Looks fine for me, @streamich what do you think?

**Comment by septs** [comment]
@streamich

**Comment by septs** [comment]
@streamich

**Comment by septs** [comment]
@streamich

**Comment by septs** [comment]
@xobotyi request merge.

**Pull request closed without merging**
