### PR TITLE
fix: use correct list variable in useList

### PR DESCRIPTION
**Pull request by xiaoboost**
Avoid referencing closure variables

### CODE REVIEW

**Comment by streamich** [comment]
@xiaoboost why did you close it?

**Comment by xiaoboost** [comment]
@streamich 
Sorry……It's my mistake……
Is it because I deleted the original branch? or some other reason?
I didn't actively close this pr.

can I create a new pr?

**Comment by streamich** [comment]
> can I create a new pr?

Of course you can.

**Pull request merged**
