### PR TITLE
feat: useUpsert

### PR DESCRIPTION
**Pull request by PetterIve**
This PR adds the `useUpsert` hook.

`useUpsert` provides a superset of `useList`, with the additional method `upsert`, which combines update or insert functionality. `useUpsert` requires that a comparison function is passed when initialising the hook.

Looking forward to your feedback!

### CODE REVIEW

**Comment by streamich** [comment]
What is your use case for this hook?

**Comment by PetterIve** [comment]
I typically find it useful have a list of "entities" (i.e. any identifiable object) which are added to, or updated, through a callback where the entity itself is passed without its list index (e.g. through a standalone form component). The hook basically wraps logic I found myself duplicating between multiple `useList` hooks.

I could make a more thorough example if you'd like.

PS: I'm not really sure if prop drilling an object's index is perforable to this approach, or if there's another way to achieve the same effect..

**Comment by streamich** [comment]
Ah, just noticed it is not in the README, maybe you want to add it on the same line with `useList`.

**Pull request merged**
